# workflow name
name: Unit Tests

# execute on events
on:
  pull_request:
    branches:
      - "main"
      - "develop"
# jobs to run
jobs:
  # install dependencies and run test command
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # 1: setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v2
      # 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm
      # 4: install dependencies with pnpm
      - name: Install dependencies
        run: pnpm install
      # 5: run test command
      - name: Run test command
        run: pnpm run test:ci
